theme = "github_dark_dimmed"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
color-modes = true
true-color = true
cursorline = true
# rulers = [100]
scrolloff = 8

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "register", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "│"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
wrap-indicator = "↪ "

[editor.search]
smart-case = true
