# 0. prefix Ctrl + a 
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# tmux output speed limit config (출력 속도 제한 설정)
# 출력 속도 조절 (단위: 밀리초)
# set -s escape-time 50

# 1. 색상 수정 (Neovim 색상이 제대로 나오게 하기 위함)
set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

# 2. keybindings
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Resize panes with prefix + h/j/k/l (repeatable with -r)
bind -r H resize-pane -L 10
bind -r J resize-pane -D 10
bind -r K resize-pane -U 10
bind -r L resize-pane -R 10

# 3. 창 번호를 1부터 시작 (키보드 0은 너무 머니까요)
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g status-position bottom

# Deliver focus events
set -g focus-events on


# 4. 직관적인 창 나누기 (| 는 수직, - 는 수평)
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"


# 5. 플러그인 목록 (TPM)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'tmux-plugins/tmux-cpu'
# set -g @plugin 'tmux-plugins/tmux-battery'

# resurrect && continuum options
set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

# yank options
# vi mode on
set-window-option -g mode-keys vi

# copy-mode vim keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

# Disable navigation when zoomed (prevents accidental unzoom)
set -g @tmux_navigator_disable_when_zoomed "1"

set -g @plugin 'TanglingTreats/tmux-everforest' # Adds to the list of plugins
set -g @tmux-everforest 'dark-hard' # Sets the option to select the theme. Also the default.
# Add '-xterm' to the back of the name for xterm256 compatibility
# E.g. 'dark-medium-xterm'



# 6. TPM 실행 (플러그인들이 정상적으로 적용되려면 반드시 파일의 맨 마지막에 있어야 함)
run '~/.config/tmux/plugins/tpm/tpm'

# 비활성 pane 테두리 살짝 밝게
set -g pane-border-style 'bg=colour239'

# 비활성 pane 배경을 살짝 밝게
set -g window-style 'bg=colour239'

# 활성 pane은 원래 터미널 배경 유지
set -g window-active-style 'bg=terminal'

